# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f922ba0205f5e03c91a1c809d5d63141cecdbfbc4e580ea7c5851509c11cb1f426dacbffc6a3a15edfeaec94915bd1b837e865c183b7d46cb15570d0bfa7b4b4

test:
  secret_key_base: 7b97c1b7f0e70518c7c75702f72e08be1beca7e68ddc6321ea853f78cf7c99af090d043788c1bdcced1fb564096fd307d38589d5fa8d67ee024a1aeaa0a9ea05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
